
name: publish on telegram on sundays.
on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 01 * * SUN'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@main
      with:
        lfs: true
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
      
    - name: Install python modules
      run: pip3 install -r requirements
      
      
    - name: add rabibasariya stories
      run: python3 rabibasariya.py

    - name: add prothomalo stories
      run: python3 onnoalo.py

    - name: generate README
      run: python3 readme-generator.py
      
    - name: publish changes
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: send to telegram
      run: python3 telegram-bot.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_USERNAME: ${{ secrets.TELEGRAM_CHANNEL_USERNAME }}
