
name: auto add stories
on:
  schedule: [cron: '37 21 * * SUN']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 13.x
      uses: actions/setup-node@master
      with:
        node-version: 13.x
      
    - name: Install
      run: yarn install
      
    - name: start job
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node index.js
      
    - name: publish changes
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
